#Primeiro Ano- Primeiro Semestre
Category.create(nome:"Marketing Estratégico", area_cientifica:"Marketing", anocurricular: 1 , semestre: 1 , creditos: 6 , codigouc: M116, tipo:"Semestral", teorica: 9, teorica_pratica: 12,pratica_laboratoriais:10, trabalho_campo: 9, seminarios: 3,orientacao_tutorial:2, estudo: 25, trabalho_grupo: 40, horas_avaliacao: 6,trabalho_projecto:40, cursos_id: 2 )
Category.create(nome:"Liderança e Negociação", area_cientifica:"Ciências Sociais e Humanas", anocurricular: 1 , semestre: 1 , creditos: 6 , codigouc: M115, tipo:"Semestral", teorica: 9, teorica_pratica: 13, trabalho_campo: 9,pratica_laboratoriais:10,seminarios: 2, orientacao_tutorial: 2, estudo: 50 ,trabalho_grupo: 30, horas_avaliacao: 6,trabalho_projecto:25, cursos_id: 2)
Category.create(nome:"Direito dos Negócios", area_cientifica:"Economia de Gestão", anocurricular: 1 , semestre: 1 , creditos: 6 , codigouc: M114, tipo:"Semestral" ,teorica: 9, teorica_pratica:14,pratica_laboratoriais: 9, trabalho_campo: 9, orientacao_tutorial: 2, seminarios: 2 , estudo: 40, trabalho_grupo: 40,trabalho_projecto: 25, horas_avaliacao: 6,cursos_id: 2)
Category.create(nome:"Gestão  de Projectos de investimento", area_cientifica:"Economia de Gestão", anocurricular: 1 , semestre: 1 , creditos: 6 , codigouc: M113, tipo:"Semestral",teorica:8, teorica_pratica:15,pratica_laboratoriais: 10, trabalho_campo:8, seminarios:2, orientacao_tutorial:2, estudo:15,trabalho_grupo:45,trabalho_projecto:45, horas_avaliacao:6 ,cursos_id: 2)
Category.create(nome:"Simulador de Gestão de Marketing", area_cientifica:"Marketing", anocurricular: 1 , semestre: 1 , creditos: 6 , codigouc: M111, tipo:"Semestral",pratica_laboratoriais:40,seminarios:5,estudo:16,trabalho_grupo:40,trabalho_projecto:45,horas_avaliacao:10,cursos_id: 2)

#Primeiro Ano- Segundo Semestre
Category.create(nome:"Desenho de Projecto", area_cientifica:"Ciências Sociais e Humanas", anocurricular: 1 , semestre: 2 , creditos: 12 , codigouc:M124 , tipo:"Semestral",teorica:10,teorica_pratica:15,pratica_laboratoriais:8,trabalho_campo:6,seminarios:4,orientacao_tutorial:2,estudo:100,trabalho_grupo:80,trabalho_projecto:80,horas_avaliacao:7,cursos_id: 2)
Category.create(nome:"Consumo", area_cientifica:"Marketing", anocurricular: 1 , semestre: 2 , creditos: 9 , codigouc:M139 , tipo:"Semestral",teorica:22,teorica_pratica:22,trabalho_campo:10,seminarios:4,orientacao_tutorial:2,estudo:140,trabalho_grupo:130,trabalho_projecto:124,horas_avaliacao:14,cursos_id: 2)
Category.create(nome:"Markeing Relacional", area_cientifica:"Marketing", anocurricular: 1 , semestre: 2 , creditos: 6 , codigouc: M125, tipo:"Semestral",teorica:10,teorica_pratica:16,pratica_laboratoriais:14,trabalho_campo:12,orientacao_tutorial:2,seminarios:6,estudo:30,trabalho_grupo:30,trabalho_projecto:30,horas_avaliacao:6,cursos_id: 2)
Category.create(nome:"Economia do Consumo", area_cientifica:"Ecnomia e Gestão", anocurricular: 1 , semestre: 2 , creditos: 6 , codigouc: M126, tipo:"Semestral",teorica:9,teorica_pratica:12,pratica_laboratoriais:10,trabalho_campo:9,orientacao_tutorial:2,seminarios:3,estudo:25,trabalho_grupo:40,trabalho_projecto:40,horas_avaliacao:6,cursos_id: 2)
Category.create(nome:"Sistemas de Análise e Apoio à Decisão", area_cientifica:"Métodos Quantitativos", anocurricular: 1 , semestre: 2, creditos: 6 , codigouc: M123, tipo:"Semestral",teorica:7,teorica_pratica:12,pratica_laboratoriais:8,trabalho_campo:14,orientacao_tutorial:2,seminarios:2,estudo:15,trabalho_grupo:45,trabalho_projecto:45,horas_avaliacao:6,cursos_id: 2)

# Segundo Ano - Primeiro Semestre
Category.create(nome:"Novas Tendências de Marketing", area_cientifica:"Marketing", anocurricular: 2 , semestre: 1 , creditos: 6 , codigouc: M121, tipo:"Semestral",teorica:12, teorica_pratica:16,pratica_laboratoriais:12, trabalho_campo:13,seminarios:5, orientacao_tutorial:2, estudo:140,trabalho_grupo:130,trabalho_projecto:124,horas_avaliacao:14,cursos_id: 2)
Category.create(nome:"Branding", area_cientifica:"Marketing", anocurricular: 2 , semestre: 1 , creditos: 9 , codigouc: M137, tipo:"Semestral",teorica:19,teorica_pratica:19, pratica_laboratoriais:9, seminarios:9, orientacao_tutorial:4,estudo:140,trabalho_grupo:130,trabalho_projecto:124,horas_avaliacao:14,cursos_id: 2)
Category.create(nome:"Direção Comercial e Vendar", area_cientifica:"Marketing", anocurricular: 2 , semestre: 1 , creditos: 9 , codigouc: M138, tipo:"Semestral",teorica:22,teorica_pratica:22,trabalho_campo:10,orientacao_tutorial:2,seminarios:4,estudo:140,trabalho_grupo:130,trabalho_projecto:124,horas_avaliacao:14,cursos_id: 2)
Category.create(nome:"Novas Tendências de Marketing", area_cientifica:"Marketing", anocurricular: 2 , semestre: 1 , creditos: 6 , codigouc: M121, tipo:"Semestral",teorica:12,teorica_pratica:16,trabalho_campo:13,pratica_laboratoriais:13,orientacao_tutorial:2,seminarios:5,estudo:140,trabalho_grupo:130,trabalho_projecto:124,horas_avaliacao:14,cursos_id: 2)
#Segundo Ano - Segundo Semestre
Category.create(nome:"Dissertação/Projeto Profissional/Estágio Profissional", area_cientifica:"Marketing", anocurricular: 2 , semestre: 2 , creditos: 30 , codigouc: M142, tipo:"Anual",teorica_pratica:30,seminarios:10,orientacao_tutorial:20,estudo:518,trabalho_projecto:504,horas_avaliacao:10,cursos_id: 2)
